using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HydroScan.dto
{
    using global::DotNetProjectParser;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Xml.Linq;

    /// <summary>
    /// A model of the Project object
    /// </summary>
    public class ProjectInfo
    {
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public ProjectInfo()
        {
        }
        public string Id { get; set; }
        /// <summary>
        /// Project name
        /// </summary>
        public string Name { get; internal set; }
        /// <summary>
        /// Full path to project
        /// </summary>
        public string FullPath { get; internal set; }

        /// <summary>
        /// Path of the project folder
        /// </summary>
        public string DirectoryPath { get; internal set; }

        /// <summary>
        /// Name of the assembly generated by project (without extension)
        /// </summary>
        public string AssemblyName { get; internal set; }

        /// <summary>
        /// The output type 
        /// </summary>
        public string OutputType { get; internal set; }

        /// <summary>
        /// The target framework
        /// </summary>
        public string TargetFramework { get; internal set; }

        /// <summary>
        /// The extension of the generated assembly
        /// </summary>
        public string TargetExtension { get; internal set; }

        /// <summary>
        /// The items included in the project
        /// </summary>
        public List<ProjectDependency> Dependencies { get; internal set; } = new List<ProjectDependency>();
        public List<string> DependencyIdList{ get; internal set; } = new List<string>();

        public string SolutionName { get; internal set; }

    }
}
